<a href="https://colab.research.google.com/github/carlosemiliorabazo/deepLearning/blob/master/2_2_Representaciones_de_Datos_para_RNA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Representaciones de datos para Redes Neuronales
- En el ejemplo anteior los datos estában en matrices multidimensionales **Numpy** también llamadas **tensores**
- Un **tensor** es un contenedor de datos, casi siempre numéricos. Una **Matriz** es un **Tensor Bidimensional**
- En un tensor, la **dimensión** se llama **eje** y el **númeor de ejes** se llama **rango*

### Tensores 0D (escalares)
- En **Numpy**, un número `float32` o `float64` es un tensor escalar
- Podemos mostrar el número de ejes de un tensor Numpy a el atributo `ndim` (en el caso del tensor escalar será igual a cero)


In [1]:
import numpy as np
x = np.array(12)
x, x.ndim

(array(12), 0)

### Tensores 1D (vectores)
- En **Numpy**, una cadena de números es un tensor 1D o **vector**
- Un **tensor 1D** tiene exactamente un **eje A**

In [2]:
x = np.array([12, 3, 6, 14, 7])
x, x.ndim

(array([12,  3,  6, 14,  7]), 1)

- Este vector de 5 entradas es un **vector 5-dimensional** (1 eje y 5 dimensiones) que no debemos confundir con un **tensor 5D** (que tendría 5 ejes, con cualquier cantidad de dimensiones a lo largo de cada eje, también llamado **tensor de rango 5**)

### Tensores 2D (matrices)
- En **Numpy**, una cadena de vectores es un tensor 2D o **matriz**
- Un **tensor 2D** tiene exactamente un **eje filas**  y un **eje colunas**

In [3]:
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
x, x.ndim

(array([[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]), 2)

### Tensores 3D y con más dimensiones
- En **Numpy**, una cadena de matrices (cubo de números) es un tensor 3D 
- Con Deep Learning solemos manipular tensores de 0D a 4D aunque si trabajamos con **video**, lo hacemos con **tensores 5D**

In [4]:
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
x, x.ndim

(array([[[ 5, 78,  2, 34,  0],
         [ 6, 79,  3, 35,  1],
         [ 7, 80,  4, 36,  2]],
 
        [[ 5, 78,  2, 34,  0],
         [ 6, 79,  3, 35,  1],
         [ 7, 80,  4, 36,  2]],
 
        [[ 5, 78,  2, 34,  0],
         [ 6, 79,  3, 35,  1],
         [ 7, 80,  4, 36,  2]]]), 3)

### Atributos Clave de un tensor
1. **Número de ejes (rango)**: es el `ndim` de Numpy
2. **Forma**: Tupla de enteros que indica cuantas dimensiones tiene el tensor en cada eje:
  - El **escalar** del ejemplo (**tensor 0D**) tiene **forma ()**
  - El **vector** del ejemplo (**tensor 1D**) tiene **forma (5,)**
  - La **matriz** del ejemplo (**tensor 2D**) tiene **forma (3,5)**
  - El **tensor 3D** del ejemplo tiene **forma (3,3,5)**)
3. **Tipo de Datos** `dtype`:
  - `float32`
  - `uint8`
  - `float64`
  - ...
  - Tensor `char` dificilmente de encontrar (no soportado por Numpy)